#%RAML 0.8

title: rover api

resourceTypes:
    - motionType:
        put:
            responses:
                200:
                    body:
                        text/plain: ~

/motion:
    /forward: &motion
        type: motionType
    /backwards: *motion
    /left: *motion
    /right: *motion
    /stop: *motion
    /status: *motion
